on:
  push:
    branches:
      - main
    paths:
      - "**.ftd"
jobs:
  everything:
    name: ft-sync
    runs-on: macos-10.15
    env:
      FT_AUTH_CODE: ${{ secrets.FT_AUTH_CODE }}
    steps:
      - uses: actions/checkout@v2
      - name: Running ft-sync status
        run: |
          chmod +x ./.github/ft-sync
          ./.github/ft-sync status
      - name: Running ft-sync sync
        run: |
          chmod +x ./.github/ft-sync
          ./.github/ft-sync sync
      - name: Running ft-sync status
        run: |
          chmod +x ./.github/ft-sync
          ./.github/ft-sync status
